<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="TRPL-PUN-0115" failures="0" tests="11" name="reviewer.ReviewerCount" time="1.783" errors="1" timestamp="2024-08-14T16:18:31 IST" skipped="10">
  <testcase classname="reviewer.ReviewerCount" name="setBrowser" time="1.782">
    <error message="Sheet index (1) is out of range (0..0)" type="java.lang.IllegalArgumentException">
      <![CDATA[java.lang.IllegalArgumentException: Sheet index (1) is out of range (0..0)
at org.apache.poi.xssf.usermodel.XSSFWorkbook.validateSheetIndex(XSSFWorkbook.java:1474)
at org.apache.poi.xssf.usermodel.XSSFWorkbook.getSheetAt(XSSFWorkbook.java:1150)
at reviewer.ReviewerCount.ReadExcel(ReviewerCount.java:43)
at reviewer.ReviewerCount.setBrowser(ReviewerCount.java:55)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.TestRunner.invokeTestConfigurations(TestRunner.java:637)
at org.testng.TestRunner.beforeRun(TestRunner.java:627)
at org.testng.TestRunner.run(TestRunner.java:589)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- setBrowser -->
  <system-out/>
  <testcase classname="reviewer.ReviewerCount" name="Login" time="0.000">
    <skipped/>
  </testcase> <!-- Login -->
  <system-out/>
  <testcase classname="reviewer.ReviewerCount" name="ReviewCountStatutoryApprove" time="0.000">
    <skipped/>
  </testcase> <!-- ReviewCountStatutoryApprove -->
  <system-out/>
  <testcase classname="reviewer.ReviewerCount" name="ReviewCountStatutoryReject" time="0.000">
    <skipped/>
  </testcase> <!-- ReviewCountStatutoryReject -->
  <system-out/>
  <testcase classname="reviewer.ReviewerCount" name="ReviewCountInternalApprove" time="0.000">
    <skipped/>
  </testcase> <!-- ReviewCountInternalApprove -->
  <system-out/>
  <testcase classname="reviewer.ReviewerCount" name="ReviewCountInternalReject" time="0.000">
    <skipped/>
  </testcase> <!-- ReviewCountInternalReject -->
  <system-out/>
  <testcase classname="reviewer.ReviewerCount" name="MyReminderStatutory" time="0.000">
    <skipped/>
  </testcase> <!-- MyReminderStatutory -->
  <system-out/>
  <testcase classname="reviewer.ReviewerCount" name="MyReminderInternal" time="0.001">
    <skipped/>
  </testcase> <!-- MyReminderInternal -->
  <system-out/>
  <testcase classname="reviewer.ReviewerCount" name="InterimReview" time="0.000">
    <skipped/>
  </testcase> <!-- InterimReview -->
  <system-out/>
  <testcase classname="reviewer.ReviewerCount" name="MyEscalation" time="0.000">
    <skipped/>
  </testcase> <!-- MyEscalation -->
  <system-out/>
  <testcase classname="reviewer.ReviewerCount" name="ReassignUser" time="0.000">
    <skipped/>
  </testcase> <!-- ReassignUser -->
  <system-out/>
</testsuite> <!-- reviewer.ReviewerCount -->
